services:
  one:
    build: .
    command: sh -c 'cd one && mix deps.get && mix phx.server'
    environment:
      OTHER_SERVICE: two
    volumes:
      - .:/usr/src/app:rw
    ports:
      - 4000:4000
  two:
    build: .
    command: sh -c 'cd two && mix deps.get && mix phx.server'
    environment:
      OTHER_SERVICE: one
      PORT: 5000
    volumes:
      - .:/usr/src/app:rw
    ports:
      - 5000:5000

networks:
  default:
    external:
      name: local_docker_hackney
